dataset :
    name : "soda_can"
    type : "ndds"
    model_dir : "/data/SameShape/turbosquid/models"
    image_dir : "/data/SameShape/Final"
    perch_debug_dir : "/data/perch_output"
    python_debug_dir : "/data/model_outputs"
python2_paths :
  - '/opt/ros/kinetic/lib/python2.7/dist-packages'
  - '/usr/local/lib/python2.7/dist-packages/'
python3_paths :
  - '/ros_python3_ws/devel/lib/python3/dist-packages'