# Inflation epsilon for the planner. Returned solution cost will be within
# inflation_epsilon of the optimal solution.
inflation_epsilon: 10
# Max time-limit for the planner. Used in conjunction with "first_solution"
# param (refer below)/
max_planning_time: 100.0 # seconds
# For non-anytime planners, if this is true, then planner will ignore time
# limit and continue searching until a solution is found.
# For anytime planners, the same as above holds, but in addition, if false,
# then planner will continue to search until epsilon has decreased to final_epsilon.
first_solution: false
# If true, planner will use lazy edge evaluations. Make sure that the
# environment supports GetLazySuccs.
use_lazy: false
